export const MOOD_EMOJIS = {
  HAPPY: '😊',
  LOVED: '🥰',
  TIRED: '😴',
  ANXIOUS: '😰',
  EXCITED: '🎉',
  SAD: '😢',
  GRATEFUL: '🙏',
  SILLY: '😜',
} as const;

export const EMOTION_ICONS = [
  { key: 'HAPPY', emoji: '😊', label: 'Happy' },
  { key: 'LOVED', emoji: '🥰', label: 'Loved' },
  { key: 'MISSING_YOU', emoji: '😢', label: 'Missing You' },
  { key: 'EXCITED', emoji: '🎉', label: 'Excited' },
  { key: 'GRATEFUL', emoji: '🙏', label: 'Grateful' },
  { key: 'SILLY', emoji: '😜', label: 'Silly' },
  { key: 'TIRED', emoji: '😴', label: 'Tired' },
  { key: 'PROUD', emoji: '💪', label: 'Proud' },
  { key: 'ROMANTIC', emoji: '💕', label: 'Romantic' },
  { key: 'LAUGHING', emoji: '😂', label: 'Laughing' },
  { key: 'BLUSHING', emoji: '☺️', label: 'Blushing' },
  { key: 'STARRY_EYED', emoji: '🤩', label: 'Starry-Eyed' },
  { key: 'WARM', emoji: '🫶', label: 'Warm' },
  { key: 'PEACEFUL', emoji: '😌', label: 'Peaceful' },
  { key: 'PLAYFUL', emoji: '😏', label: 'Playful' },
  { key: 'ADORING', emoji: '😍', label: 'Adoring' },
] as const;

export const VIRTUAL_DATE_IDEAS = [
  'Watch the same movie together on a video call 🎬',
  'Cook the same recipe simultaneously 👨‍🍳',
  'Have a virtual picnic — set up blankets and snacks! 🧺',
  'Play an online game together 🎮',
  'Do a virtual museum tour together 🏛️',
  'Read the same book and discuss it 📚',
  'Have a virtual dinner date with candles 🕯️',
  'Do a workout video together 💪',
  'Watch the sunset/sunrise at your locations 🌅',
  'Play 20 questions about each other ❓',
  'Have a talent show — show off a skill! 🎤',
  'Draw portraits of each other 🎨',
  'Take a virtual walk and share your surroundings 🚶',
  'Plan your next trip together on a map 🗺️',
  'Write love letters and read them aloud 💌',
  'Have a themed dress-up night 👗',
  'Star-gaze together while on a call ✨',
  'Share childhood photos and stories 📷',
  'Do a puzzle together using a shared screen 🧩',
  'Have a dessert-making challenge 🍰',
];

export const DAILY_QUESTIONS = [
  "What's one thing about me that always makes you smile?",
  'If we could teleport anywhere right now, where would you take us?',
  "What's your favorite memory of us so far?",
  'What song reminds you of us?',
  "What's something new you'd like us to try together?",
  'What do you think makes our relationship special?',
  'If we had a whole day with no plans, what would you want to do?',
  "What's the most thoughtful thing I've ever done for you?",
  "What's one dream you have for our future?",
  'What quality of mine do you admire most?',
  "What's a small thing I do that means a lot to you?",
  'If we could relive one day together, which would it be?',
  "What's something you've always wanted to tell me?",
  'What fictional couple reminds you of us?',
  "What's the funniest thing that's happened to us?",
  'What are you most grateful for in our relationship?',
  "If you could give our love story a title, what would it be?",
  "What's one thing you want us to accomplish together this year?",
  "What's your love language today?",
  "What's a challenge we've overcome that made us stronger?",
  'What do you look forward to most about our future?',
  "What's the best advice about love you've ever received?",
  "If you could describe our relationship in one word, what would it be?",
  "What's something I do that makes you feel safe?",
  'What are three things you love about us?',
  'What moment made you realize you loved me?',
  "What's your favorite way to spend quality time together?",
  "What's a tradition you'd like us to start?",
  'What makes you feel most connected to me?',
  'What are you most excited about in our relationship right now?',
];
